// This worker loads the Shade WASM module and processes commands
// from the main thread. The OffscreenCanvas is transferred here.
// The WASM module is built separately via `scripts/build-wasm.sh` (wasm-pack).

// eslint-disable-next-line @typescript-eslint/no-explicit-any
let wasm: any = null;

// Message protocol:
// { type: "init" } → { type: "ready" }
// { type: "load_image_encoded", bytes: Uint8Array, fileName?: string } → { type: "image_loaded", layerCount: number, canvasWidth: number, canvasHeight: number }
// { type: "apply_tone", layerIdx: number, exposure: number, ... } → { type: "tone_applied" }
// { type: "get_stack" } → { type: "stack", data: string }

self.onmessage = async (e: MessageEvent) => {
  const msg = e.data;

  switch (msg.type) {
    case "init": {
      try {
        // Dynamic import of the WASM module (built via scripts/build-wasm.sh).
        // @vite-ignore suppresses Vite's static resolution — the file is generated at build time.
        // @ts-expect-error Generated by the WASM build step and not part of TS sources.
        wasm = await import(/* @vite-ignore */ "../../wasm/shade_wasm.js");
        await wasm.default?.();
        self.postMessage({ type: "ready" });
      } catch (err) {
        self.postMessage({ type: "error", message: String(err) });
      }
      break;
    }

    case "load_image_encoded": {
      if (!wasm) {
        self.postMessage({ type: "error", message: "WASM not initialised" });
        return;
      }
      const info = await wasm.load_image_encoded(msg.bytes, msg.fileName ?? null);
      self.postMessage({
        type: "image_loaded",
        layerCount: info.layer_count,
        canvasWidth: info.canvas_width,
        canvasHeight: info.canvas_height,
        source_bit_depth: info.source_bit_depth,
      });
      break;
    }

    case "apply_tone": {
      if (!wasm) return;
      wasm.apply_tone(
        msg.layerIdx,
        msg.exposure,
        msg.contrast,
        msg.blacks,
        msg.whites ?? 0.0,
        msg.highlights,
        msg.shadows,
        msg.gamma ?? 1.0,
      );
      self.postMessage({ type: "tone_applied" });
      break;
    }

    case "apply_color": {
      if (!wasm) return;
      wasm.apply_color(
        msg.layerIdx,
        msg.saturation,
        msg.vibrancy,
        msg.temperature,
        msg.tint,
      );
      self.postMessage({ type: "color_applied" });
      break;
    }

    case "apply_hsl": {
      if (!wasm) return;
      wasm.apply_hsl(
        msg.layerIdx,
        msg.red_hue ?? 0,
        msg.red_sat ?? 0,
        msg.red_lum ?? 0,
        msg.green_hue ?? 0,
        msg.green_sat ?? 0,
        msg.green_lum ?? 0,
        msg.blue_hue ?? 0,
        msg.blue_sat ?? 0,
        msg.blue_lum ?? 0,
      );
      self.postMessage({ type: "hsl_applied" });
      break;
    }

    case "set_layer_visible": {
      if (!wasm) return;
      wasm.set_layer_visible(msg.layerIdx, msg.visible);
      self.postMessage({ type: "layer_updated" });
      break;
    }

    case "set_layer_opacity": {
      if (!wasm) return;
      wasm.set_layer_opacity(msg.layerIdx, msg.opacity);
      self.postMessage({ type: "layer_updated" });
      break;
    }

    case "move_layer": {
      if (!wasm) return;
      const layerIdx = wasm.move_layer(msg.fromIdx, msg.toIdx);
      self.postMessage({ type: "layer_moved", layerIdx });
      break;
    }

    case "get_stack": {
      if (!wasm) return;
      const json = wasm.get_stack_json();
      self.postMessage({ type: "stack", data: json });
      break;
    }

    case "render_preview": {
      if (!wasm) return;
      const [width, height] = wasm.get_canvas_size();
      const pixels = wasm.render_preview_rgba();
      self.postMessage({ type: "preview_rendered", pixels, width, height });
      break;
    }

    default:
      self.postMessage({
        type: "error",
        message: `unknown message type: ${msg.type}`,
      });
  }
};
